name: Run tests and build docs
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v7
    - name: Install Conda and environment
      uses: conda-incubator/setup-miniconda@v4
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
        environment-file: dynamicisttoolkit-dev-env.yml
        activate-environment: dynamicisttoolkit-dev
        miniforge-version: latest
    - name: Run pytest with coverage
      shell: bash -l {0}
      run: |
        coverage run -m pytest
        pytest --doctest-modules dtk/
    - name: Build the documentation
      shell: bash -l {0}
      run: |
        cd docs && make html SPHINXOPTS="-W --keep-going"
    - name: Install the software
      shell: bash -l {0}
      run: |
        python setup.py install
